return {
  "catppuccin/nvim",
  config = function()
    require("catppuccin").setup({
      flavour = "mocha",
      lazy = false,
      priority = 1000,
      transparent_background = true,
      highlight_overrides = {
        mocha = function(colors)
          return {
            CurSearch = { bg = colors.sky },
            IncSearch = { bg = colors.sky },
            CursorLineNr = { fg = colors.blue, style = { "bold" } },
            DashboardFooter = { fg = colors.overlay0 },
            TreesitterContextBottom = { style = {} },
            WinSeparator = { fg = colors.overlay0, style = { "bold" } },
            ["@markup.italic"] = { fg = colors.blue, style = { "italic" } },
            ["@markup.strong"] = { fg = colors.blue, style = { "bold" } },
            Headline = { style = { "bold" } },
            Headline1 = { fg = colors.blue, style = { "bold" } },
            Headline2 = { fg = colors.pink, style = { "bold" } },
            Headline3 = { fg = colors.lavender, style = { "bold" } },
            Headline4 = { fg = colors.green, style = { "bold" } },
            Headline5 = { fg = colors.peach, style = { "bold" } },
            Headline6 = { fg = colors.flamingo, style = { "bold" } },
            rainbow1 = { fg = colors.blue, style = { "bold" } },
            rainbow2 = { fg = colors.pink, style = { "bold" } },
            rainbow3 = { fg = colors.lavender, style = { "bold" } },
            rainbow4 = { fg = colors.green, style = { "bold" } },
            rainbow5 = { fg = colors.peach, style = { "bold" } },
            rainbow6 = { fg = colors.flamingo, style = { "bold" } },
          }
        end,
      },
      color_overrides = {
        mocha = {
          rosewater = "#ff8855",
          flamingo  = "#ff4466",
          pink      = "#dd77ff",
          mauve     = "#aa77ff",
          red       = "#ff3344",
          maroon    = "#ff5588",
          peach     = "#ffaa44",
          yellow    = "#ffcc44",
          green     = "#99ee55",
          teal      = "#44ddcc",
          sky       = "#66ccff",
          sapphire  = "#5588ff",
          blue      = "#4499ff",
          lavender  = "#aaaaff",
          text      = "#c6c6c6",
          subtext1  = "#a8a8a8",
          subtext0  = "#8c8c8c",
          overlay2  = "#6e6e6e",
          overlay1  = "#585858",
          overlay0  = "#444444",
          surface2  = "#2a2a2a",
          surface1  = "#1a1a1a",
          surface0  = "#111111",
          base      = "#080808",
          mantle    = "#050505",
          crust     = "#020202",
        },
      },
      integrations = {
        telescope = {
          enabled = true,
          style = "nvchad",
        },
      },
    })
    vim.cmd([[colorscheme catppuccin]])
  end,
}
